import assert from 'node:assert/strict';
import { MongoMemoryServer } from 'mongodb-memory-server';
import { MongoClient } from 'mongodb';
import { handler } from '../netlify/functions/club.mjs';
import { loadEngine } from '../netlify/functions/lib/engine.mjs';
import { viewerRecommendations } from '../netlify/functions/lib/viewer.mjs';
import { passwordHash, passwordMatches, safeProfile, publicUser } from '../netlify/functions/lib/club-security.mjs';

const hash=passwordHash('test-password-long-123');
assert.ok(passwordMatches('test-password-long-123',hash));assert.ok(!passwordMatches('wrong-password-123',hash));
assert.ok(!JSON.stringify(publicUser({id:'1',name:'A',password:hash,email:'private@example.com',provider:'email'})).includes('private'));
const engine=loadEngine();
assert.throws(()=>safeProfile({ratings:{1:3.7},genres:[]},engine));
const recommendations=viewerRecommendations(engine,{preferred_genres:['Sci-Fi'],survey:{avoid:['Horror']},exclude_ids:[2571],minimum_rating:3.5,k:20});
assert.ok(recommendations.count>0);assert.ok(recommendations.recommendations.every(m=>!m.genres.includes('Horror')&&m.movie_id!==2571&&m.rating>=3.5));
assert.throws(()=>viewerRecommendations(engine,{minimum_rating:6}));
const empty=viewerRecommendations(engine,{year_min:2199,year_max:2200,k:20});assert.equal(empty.count,0);
delete process.env.MONGODB_URI;
assert.equal(JSON.parse((await handler({path:'/club/config',httpMethod:'GET'})).body).online,false);
const server=await MongoMemoryServer.create({binary:{version:'8.0.15'},instance:{dbName:'cine_test'}});
process.env.MONGODB_URI=server.getUri();process.env.MONGODB_DB='cine_test';process.env.SITE_URL='https://cine-test.example';process.env.ADMIN_EMAIL='test@example.com';
let checks=0;
const call=async(path,method='GET',body,cookie,extra={})=>{const result=await handler({path:'/club'+path,httpMethod:method,headers:{origin:process.env.SITE_URL,...(cookie?{cookie}:{}),...extra},queryStringParameters:{},body:body===undefined?undefined:JSON.stringify(body)});checks++;return {...result,data:JSON.parse(result.body || '{}')};};
try{
  const a=await call('/auth/register','POST',{email:'test@example.com',password:'test-password-long-123',name:'Viewer A'});assert.equal(a.statusCode,200);assert.equal(a.data.user.role,'member');
  const cookieA=a.multiValueHeaders['Set-Cookie'][0].split(';')[0];assert.ok(a.multiValueHeaders['Set-Cookie'][0].includes('HttpOnly; Secure; SameSite=Lax'));
  const b=await call('/auth/guest','POST',{name:'Ignored',anonymous:true});assert.equal(b.data.user.name,'Ẩn danh');const cookieB=b.multiValueHeaders['Set-Cookie'][0].split(';')[0];
  assert.equal((await call('/profile')).statusCode,401);
  assert.equal((await call('/profile','PUT',{ratings:{1:4.5},watchlist:[2],seen:[1],genres:['Comedy'],survey:{mood:'gentle'}},cookieA)).statusCode,200);
  assert.equal((await call('/profile','GET',undefined,cookieA)).data.ratings['1'],4.5);
  assert.equal(Object.keys((await call('/profile','GET',undefined,cookieB)).data.ratings).length,0);
  assert.equal((await call('/profile','PUT',{ratings:{1:5.1},genres:[]},cookieA)).statusCode,422);
  assert.equal((await call('/auth/login','POST',{email:'test@example.com',password:'wrong-password-123'})).statusCode,401);
  assert.equal((await call('/auth/login','POST',{email:'test@example.com',password:'test-password-long-123'})).statusCode,200);
  const post=await call('/posts','POST',{kind:'blog',title:'A film worth discussing',content:'This is a test blog with enough text for schema validation.',anonymous:true},cookieA);assert.equal(post.statusCode,201);assert.equal(post.data.status,'published');
  assert.equal((await call('/posts/'+post.data.id+'/delete','POST',{},cookieB)).statusCode,403);
  assert.equal((await call('/posts/'+post.data.id+'/report','POST',{reason:'Test reporting workflow'},cookieB)).statusCode,200);
  assert.equal((await call('/posts/'+post.data.id+'/like','POST',{},cookieB)).statusCode,200);
  await call('/posts/'+post.data.id+'/like','POST',{},cookieB);
  assert.equal((await call('/feedback','POST',{category:'idea',score:4,content:'Test feedback for the website.'},cookieB)).statusCode,201);
  assert.equal((await call('/feedback','POST',{content:'Good feedback'},cookieA,{origin:'https://other.example'})).statusCode,403);
  const review={kind:'review',movieId:1,rating:4.5,content:'A lovely movie.'};
  assert.equal((await call('/posts','POST',review,cookieA)).statusCode,201);await call('/posts','POST',{...review,rating:5},cookieA);
  const client=new MongoClient(server.getUri());await client.connect();const db=client.db('cine_test');
  assert.equal(await db.collection('posts').countDocuments({kind:'review',movieId:1}),1);
  assert.equal((await db.collection('posts').findOne({id:post.data.id})).likes,1);
  assert.equal(await db.collection('reports').countDocuments(),1);
  await assert.rejects(()=>db.collection('posts').insertOne({id:'bad',userId:'fake',author:'A',kind:'wrong',status:'published',content:'test',createdAt:new Date()}));
  assert.ok(!(await db.collection('users').findOne({id:a.data.user.id})).password.includes('test-password-long-123'));
  assert.equal((await call('/auth/delete','POST',{password:'wrong-password'},cookieA)).statusCode,401);
  assert.equal((await call('/auth/delete','POST',{},cookieB)).statusCode,200);
  assert.equal((await call('/profile','GET',undefined,cookieB)).statusCode,401);
  assert.equal(await db.collection('users').countDocuments({id:b.data.user.id}),0);
  await client.close();
  assert.equal((await call('/posts/'+post.data.id+'/delete','POST',{},cookieA)).statusCode,200);
  assert.equal((await call('/auth/logout','POST',{},cookieA)).statusCode,200);
  assert.equal((await call('/profile','GET',undefined,cookieA)).statusCode,401);
  console.log(`PASS: ${checks} MongoDB API calls; authentication, profile isolation, anonymous guests, public blogs, reporting, likes, ownership, half-stars, JSON Schema and viewer filters.`);
}finally{await server.stop();}
process.exit(0);
