import assert from 'node:assert/strict';
import {Engine,ValidationError} from '../netlify/functions/lib/engine.mjs';
import {viewerRecommendations} from '../netlify/functions/lib/viewer.mjs';
import films from '../web/film-utils.js';

const movie=(id,title,genres,rating,year=2026,external_ratings=[])=>({movie_id:id,title,genres,rating,year,external_ratings,rating_count:rating?100:0,bayesian_rating:rating});
const rows=[movie(1,'Classic Orbit','Sci-Fi',4.2,1999),movie(2,'New Orbit','Sci-Fi',null,2026,[{provider:'IMDb',audience:'audience',value:8.8,scale:10}]),movie(3,'A Fearful Night','Horror',5),movie(4,'Low Orbit','Sci-Fi|Adventure',2.5),movie(5,'Unknown Orbit','Sci-Fi',null,2026,[{provider:'Rotten Tomatoes',audience:'audience',value:95,scale:100},{provider:'Metacritic',audience:'critics',value:90,scale:100}]),movie(6,'A Love Story','Romance|Drama',5)];
const engine=new Engine({movies:rows,movie_ids:rows.map(m=>m.movie_id),user_ids:[],genres:['Sci-Fi','Adventure','Horror','Romance','Drama']});
const result=viewerRecommendations(engine,{preferred_genres:['sci-fi'],minimum_rating:4,survey:{avoid:['Horror'],mood:'wonder'},k:20});
assert.deepEqual(result.recommendations.map(m=>m.movie_id),[2,1]);
assert.equal(result.recommendations[0].audience_rating.provider,'IMDb');assert.equal(result.recommendations[0].audience_rating.value,8.8);
assert.equal(films.audienceRating(rows[4]),null); // Percent approval and critics are not average audience stars.
assert.ok(result.recommendations.every(m=>m.reason.includes('Khoa học viễn tưởng')));
assert.equal(viewerRecommendations(engine,{preferred_genres:['Sci-Fi'],survey:{era:'2026:2026'},minimum_rating:4}).count,1);
assert.equal(viewerRecommendations(engine,{preferred_genres:['Sci-Fi'],exclude_ids:['1'],ratings:{2:.5},minimum_rating:4}).count,0);
assert.ok(!viewerRecommendations(engine,{survey:{seed_ids:[1]},k:20}).recommendations.some(m=>m.movie_id===1));
for(const payload of [{ratings:{1:0}},{ratings:{1:3.7}},{preferred_genres:'Sci-Fi'},{preferred_genres:['Sci-Fi'],survey:{avoid:['Sci-Fi']}},{survey:{avoid:['unknown']}},{survey:{era:'future'}},{survey:{mood:'unknown'}},{survey:{seed_ids:[999]}}])assert.throws(()=>viewerRecommendations(engine,payload),ValidationError);
assert.equal(viewerRecommendations(engine,{preferred_genres:['Sci-Fi'],year_min:2199,k:20}).count,0);

const library=[{...rows[0],title:'Orbit, The',my_rating:.5},{...rows[1],title:'Ám ảnh',my_rating:4.5},{...rows[4],title:'Điện ảnh'}];
assert.deepEqual(films.collectionMovies(library,{q:'am anh'}).map(m=>m.movie_id),[2]);
assert.deepEqual(films.collectionMovies(library,{q:'dien anh'}).map(m=>m.movie_id),[5]);
assert.deepEqual(films.collectionMovies(library,{status:'rated',sort:'personal'}).map(m=>m.movie_id),[2,1]);
assert.deepEqual(films.collectionMovies(library,{status:'unrated'}).map(m=>m.movie_id),[5]);
assert.deepEqual(films.collectionMovies(library,{yearMin:2026,yearMax:2026,sort:'rating'}).map(m=>m.movie_id),[2,5]);
assert.deepEqual(library.map(m=>m.movie_id),[1,2,5]);
assert.equal(films.displayTitle('Orbit, The'),'The Orbit');
const searchable={...rows[0],title:'The Matrix',title_vi:'Ma trận',imdb_id:'tt0133093',directors:['Lana Wachowski'],year:1999};
for(const q of ['ma tran','Wachowski 1999','matrix 1999','tt0133093'])assert.ok(films.matchesQuery(searchable,q));
assert.equal(films.searchSuggestions([searchable],'matrx')[0].title,'The Matrix');
assert.deepEqual(films.searchSuggestions([searchable],'xy'),[]);
const future={...rows[0],release:{date:'2099-10-10',region:'US'}};
assert.equal(films.releaseState(future,'2026-10-09'),'upcoming');
assert.equal(films.matchesRelease(future,'upcoming','2026-10-09'),true);
assert.equal(films.matchesRelease(future,'vn-upcoming','2026-10-09'),false);
const vietnam={...rows[0],release:{date:'2026-09-25',region:'VN'},cinema_status:{status:'now',region:'VN',checked_at:'2026-10-09'}};
assert.equal(films.matchesRelease(vietnam,'vn-now','2026-10-09'),true);
assert.equal(films.matchesRelease(vietnam,'vn-now','2026-10-17'),false);
assert.equal(films.matchesRelease(vietnam,'released','2026-10-09','VN'),false);
assert.equal(films.matchesRelease(vietnam,'released','2026-10-17','VN'),true);
const releaseEngine=new Engine({movies:[future],movie_ids:[1],user_ids:[],genres:['Sci-Fi']});
assert.equal(viewerRecommendations(releaseEngine,{k:20}).count,0);
assert.equal(viewerRecommendations(releaseEngine,{k:20,release:'upcoming'}).count,1);
assert.throws(()=>viewerRecommendations(releaseEngine,{release:'wrong'}),ValidationError);
const searchEngine=new Engine({movies:[searchable],movie_ids:[1],user_ids:[],genres:['Sci-Fi']});
assert.equal(searchEngine.catalog({q:'ma tran'}).total,1);
assert.equal(searchEngine.catalog({q:'matrx'}).suggestions[0].movie_id,1);
const multiple={...rows[0],release:{region:'US',date:'2026-10-02'},releases:[{region:'JP',date:'2026-10-16'}]};
assert.equal(films.matchesRelease(multiple,'recent','2026-10-09','US'),true);
assert.equal(films.matchesRelease(multiple,'upcoming','2026-10-09','JP'),true);
assert.equal(films.matchesRelease(multiple,'upcoming','2026-10-09','US'),false);
assert.equal(films.matchesRelease(multiple,'released','2026-10-09','US'),true);
assert.equal(films.matchesRelease(multiple,'released','2026-10-09','JP'),false);
assert.equal(films.matchesRelease(multiple,'screening','2026-10-09','US'),false);
assert.equal(films.matchesRelease({...rows[0]},'released','2026-10-09','US'),false);
assert.equal(films.unreleased(multiple,'2026-10-09'),false);
assert.equal(films.unreleased(multiple,'2026-10-09','JP'),true);
assert.equal(films.matchesRelease(multiple,'all','2026-10-09','KR'),false);
assert.throws(()=>searchEngine.catalog({release_region:'ZZ'}),ValidationError);
console.log('PASS: modern-film audience ratings, honest score sources, genre/era exclusions, survey validation and collection search/sorting.');
